version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    image: sonictouch/frontend
    ports:
      - "8080:80"
    networks:
      - appnet

  server:
    build: ./server
    image: sonictouch/backend
    ports:
      - "5000:5000"
    volumes:
      - ./server/mongodb-data:/app/mongodb-data
    networks:
      - appnet
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/sonic-touch
      - CLIENT_URL=http://localhost:8080

  rasa:
    build: ./rasa
    image: sonictouch/rasa
    ports:
      - "5005:5005"
    networks:
      - appnet
    depends_on:
      - actions
    volumes:
      - ./rasa/models:/app/models

  actions:
    build:
      context: .
      dockerfile: ./rasa/actions/Dockerfile
    image: sonictouch/rasa-actions
    ports:
      - "5055:5055"
    networks:
      - appnet

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - appnet

volumes:
  mongodb_data:

networks:
  appnet:
